- name: Validate {{ item }} is installed
  command: >
    "rpm -qa | grep {{ item }}"
  with_items: "{{ libvirt_pkgs }}"
  register: installed_rpms
  become: True
  ignore_errors: yes
  failed_when: installed_rpms.stdout == ""
  tags:
    - validate
    - validate_pkgs