- name: Gather the rpm package facts
  package_facts:
    manager: auto
  become: True
  tags:
    - validate
    - validate_pkgs

- name: Validate {{ item }} is installed
  fail:
    msg: "{{ item }} is not installed"
  when: "{{ item }} not in ansible_facts.packages"
  loop: "{{ package_list }}"
  ignore_errors: yes
  become: True   
  tags:
    - validate
    - validate_pkgs