- name: Validate {{ libvirt_install_dir }} exists
  stat:
    path: "{{ libvirt_install_dir }}"
  register: lvm_path
  become: True 
  ignore_errors: yes
  failed_when: lvm_path.stat.isdir == false and lvm_path.stat.exists == false
  tags:
    - validate
    - validate_fs

- name: Validate {{ libvirt_install_dir }} is mounted
  lineinfile: 
    dest: '/etc/fstab'
    regexp: '(^.*libvirt.*$)'
    state: present
    check_mode: yes
  register: libvirt_path
  become: True 
  ignore_errors: yes
  failed_when: libvirt_path.changed
  tags:
    - validate
    - validate_fs