- name: Validate system is registered to Red Hat
  shell: >
    subscription-manager status| grep ^Overall
  register: subscription_status
  become: True
  ignore_errors: yes
  changed_when: false
  tags:
    - validate
    - validate_rhsm

- name: Fail when Subscription status is not current
  fail: msg="Bailing out.  Subscription status is not current"
  when: "'Current' not in subscription_status.stdout"
