- name: Validate {{ libvirt_install_dir }} exists
  stat:
    path: "{{ libvirt_install_dir }}"
  register: lvm_path
  become: True
  ignore_errors: yes
  tags:
    - validate
    - validate_fs

- name: Fail when  {{ libvirt_install_dir }} does not  exist
  fail: msg="Bailing out. {{ libvirt_install_dir }} does not  exist."
  when:  not lvm_path.stat.isdir|bool and not lvm_path.stat.exists|bool


- name: Validate {{ libvirt_install_dir }} is mounted
  lineinfile:
    dest: '/etc/fstab'
    regexp: '(^.*libvirt.*$)'
    state: present
    check_mode: yes
  register: libvirt_path
  become: True
  ignore_errors: yes
  failed_when: libvirt_path.changed
  tags:
    - validate
    - validate_fs

- name: "Confirm that  {{ qcow_rhel_name }} exists under the {{ project_dir }}"
  stat:
    path: "{{ project_dir }}/{{ os_qcow_image_name }}"
  register: main_qcow_check
  become: True
  ignore_errors: yes

- name: Fail when {{ project_dir }}/{{ os_qcow_image_name }} does not exist
  fail: msg="Bailing out. {{ project_dir }}/{{ os_qcow_image_name }} does not exist"
  when: not main_qcow_check.stat.exists or main_qcow_check is undefined

- name: "Confirm that  {{ qcow_rhel_name }} exists under the {{ project_dir }}"
  stat:
    path: "{{ kvm_host_libvirt_dir }}/{{ os_qcow_image_name }}"
  register: kvm_qcow_check
  become: True
  ignore_errors: yes

- name: Fail when {{ kvm_host_libvirt_dir }}/{{ os_qcow_image_name }} does not exist
  fail: msg="Bailing out. {{ kvm_host_libvirt_dir }}/{{ os_qcow_image_name }} does not exist"
  when: not kvm_qcow_check.stat.exists or kvm_qcow_check is undefined