- name: Validate {{ lvm_dir }} exists
  stat:
    path: "{{ lvm_dir }}"
  register: lvm_path
  become: True 
  ignore_errors: yes
  failed_when:  not lvm_path.stat.isdir and lvm_path.stat.isdir is not defined
  tags:
    - validate
    - validate_fs

- name: Validate {{ lvm_dir }} is mounted
  lineinfile: 
    dest: '/etc/fstab'
    line: "user"
    regexp: '(^.*libvirt.*$)'
    check_mode: yes
  register: libvirt_path
  become: True 
  ignore_errors: yes
  failed_when: libvirt_path.changed
  tags:
    - validate
    - validate_fs