- name: "Validate {{ item }} is installed"
  yum:
    list: "{{ item }}"
  with_items: "{{ libvirt_pkgs }}"
  register: installed_pkg
  become: True
  ignore_errors: yes
  failed_when: not installed_pkg
  tags:
    - validate
    - validate_pkgs