- name: Validate {{ libvirt_install_dir }} exists
  stat:
    path: "{{ libvirt_install_dir }}"
  register: lvm_path
  become: True 
  ignore_errors: yes
  failed_when: lvm_path.stat.isdir == false and lvm_path.stat.exists == false
  tags:
    - validate
    - validate_fs

- name: Validate {{ libvirt_install_dir }} is mounted
  lineinfile: 
    dest: '/etc/fstab'
    regexp: '(^.*libvirt.*$)'
    state: present
    check_mode: yes
  register: libvirt_path
  become: True 
  ignore_errors: yes
  failed_when: libvirt_path.changed
  tags:
    - validate
    - validate_fs

- name: "Validate file exists under the {{ project_dir }}"
  stat:
    path: "{{ project_dir }}/rhel-server-7.6-x86_64-kvm.qcow2"
  with_items: "{{ libvirt_host_networks }}"
  register: result_dir
  become: True 
  ignore_errors: yes
  failed_when: not result_dir.stat.exists
  tags:
    - validate
    - validate_fs